### ISSUE TITLE
Unable to run the exmaple with current Wildfly

### ISSUE THREAD

**Issue by red-hood** [mstahv/jpa-invoicer#27]
When deployin the war file to a Wildfly 10.1, the following exceptions happen:

22:24:21,280 ERROR [org.jboss.msc.service.fail](ServerService Thread Pool -- 62) MSC000001: Failed to start service jboss.persistenceunit."invoicer-1.0-SNAPSHOT.war#invoicerdb": org.jboss.msc.service.StartException in service jboss.persistenceunit."invoicer-1.0-SNAPSHOT.war#invoicerdb": javax.persistence.PersistenceException: [PersistenceUnit: invoicerdb] Unable to build Hibernate SessionFactory

It would be nice to be able to run the example, as it is referenced from the official documentation.

**Comment by markjkelly** [comment]
I was able to get past this error by changing the FetchType to Lazy in the User class:
@ManyToMany(mappedBy = "administrators", fetch = FetchType.LAZY)

Hibernate was complaining about simultaneously fetching multiple bags

**Comment by kalwar** [comment]
Yes that does make it run. But now complains about "the requested view was not available"

And, there is this type of error message which does not initialize:
`Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role:`

**Comment by mstahv** [comment]
@kalwar How did you get that exception? I wasn't able to reproduce that issue. If you can still reproduce the issue, please let me know and let's fix it.

**Comment by kalwar** [comment]
Thanks for asking that question. After your pom.xml update I am getting this:
`[ERROR] Plugin com.vaadin:vaadin-maven-plugin>:7.7.4 or one of its dependencies could not be resolved: Could not find artifact com.vaadin:vaadin-maven-plugin>:jar:7.7.4 in viritin (http://virit.in/maven2)`

**Comment by mstahv** [comment]
That's weird. Vaadin 7.7.4 should be in maven central since yesterday. Could you try with:

```
 mvn -U clean package
```

**Comment by kalwar** [comment]
Thanks for your help. Something fishy in my pom.xml, I'll have to check... it shows something like this:
`Downloading: http://virit.in/maven2/com/vaadin/vaadin-maven-plugin%3E/7.7.4/vaadin-maven-plugin%3E-7.7.4.pom`

**Comment by mstahv** [comment]
Based on the message looks like there is an extra > character in vaadin-maven-plugin declaration? I double checked and there shouldn't be one in the repositorys pom.xml, but check yours anyway.

**Comment by kalwar** [comment]
@mstahv Thanks it actually compiles now but sadly it still fails to deploy says 
`Caused by: org.apache.maven.plugin.MojoExecutionException: The server failed to start
    at org.wildfly.plugin.server.RunMojo.doExecute(RunMojo.java:212)`

**Comment by mstahv** [comment]
Another server in the same port (8080)? If not, let me see the full error and let's fix it.

**Comment by kalwar** [comment]
```
[ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.0.2.Final:run (default-cli) on project jpa-test: The server failed to start: Deployment failed and was rolled back. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.0.2.Final:run (default-cli) on project jpa-test: The server failed to start
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: The server failed to start
    at org.wildfly.plugin.server.RunMojo.doExecute(RunMojo.java:212)
    at org.wildfly.plugin.deployment.AbstractDeployment.execute(AbstractDeployment.java:111)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    ... 20 more
Caused by: org.wildfly.plugin.common.DeploymentExecutionException: Deployment failed and was rolled back.
    at org.wildfly.plugin.deployment.standalone.StandaloneDeployment.execute(StandaloneDeployment.java:180)
    at org.wildfly.plugin.deployment.AbstractDeployment.executeDeployment(AbstractDeployment.java:121)
    at org.wildfly.plugin.server.RunMojo.doExecute(RunMojo.java:197)
    ... 23 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by mstahv** [comment]
"Deployment failed", so there is probably some earlier message with the real issue.

**Comment by kalwar** [comment]
```
service jboss.deployment.unit."jpa-test-1.0-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START (missing) dependents: [service jboss.undertow.deployment.default-server.default-host./jpa-test, service jboss.deployment.unit."jpa-test-1.0-SNAPSHOT.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host./jpa-test.UndertowDeploymentInfoService] 

...UndertowDeploymentInfoService (missing) dependents: [service jboss.undertow.deployment.default-server.default-host...

00:51:40,447 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0236: Suspending server with no timeout.
00:51:40,450 INFO  [org.jboss.as.server] (Management Triggered Shutdown) WFLYSRV0241: Shutting down in response to management operation 'shutdown'
00:51:40,478 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-5) WFLYJCA0010: Unbound data source [java:jboss/datasources/ExampleDS]
00:51:40,484 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0019: Host default-host stopping
00:51:40,489 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0008: Undertow HTTPS listener https suspending
00:51:40,491 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0007: Undertow HTTPS listener https stopped, was bound to 127.0.0.1:8443
00:51:40,497 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0008: Undertow HTTP listener default suspending
00:51:40,498 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) WFLYUT0007: Undertow HTTP listener default stopped, was bound to 127.0.0.1:8080
00:51:40,499 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0004: Undertow 1.4.0.Final stopping
00:51:40,504 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-2) WFLYJCA0019: Stopped Driver service with driver-name = h2
00:51:40,537 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0050: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) stopped in 77ms
```

**Comment by kalwar** [comment]
I am not sure, if hope this gives more info:

```
00:51:40,305 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 58) MSC000001: Failed to start service jboss.persistenceunit."jpa-1.0-SNAPSHOT.war#jpa-testdb": org.jboss.msc.service.StartException in service jboss.persistenceunit."jpa-test-1.0-SNAPSHOT.war#jpa-testdb": javax.persistence.PersistenceException: [PersistenceUnit: jpa-testdb] Unable to build Hibernate SessionFactory
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:179)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:121)
    at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:667)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:193)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: jpa-testdb] Unable to build Hibernate SessionFactory
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:954)
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:882)
    at org.jboss.as.jpa.hibernate5.TwoPhaseBootstrapImpl.build(TwoPhaseBootstrapImpl.java:44)
    at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:161)
    ... 7 more
Caused by: org.hibernate.loader.MultipleBagFetchException: cannot simultaneously fetch multiple bags: [com.bcplatforms.backend.JPATest.invoiceRows, com.bcplatforms.backend.User.administrates]
    at org.hibernate.loader.plan.exec.internal.AbstractLoadQueryDetails.generate(AbstractLoadQueryDetails.java:178)
    at org.hibernate.loader.plan.exec.internal.EntityLoadQueryDetails.<init>(EntityLoadQueryDetails.java:89)
    at org.hibernate.loader.plan.exec.internal.BatchingLoadQueryDetailsFactory.makeEntityLoadQueryDetails(BatchingLoadQueryDetailsFactory.java:61)
    at org.hibernate.loader.entity.plan.AbstractLoadPlanBasedEntityLoader.<init>(AbstractLoadPlanBasedEntityLoader.java:82)
    at org.hibernate.loader.entity.plan.EntityLoader.<init>(EntityLoader.java:103)
    at org.hibernate.loader.entity.plan.EntityLoader.<init>(EntityLoader.java:38)
    at org.hibernate.loader.entity.plan.EntityLoader$Builder.byUniqueKey(EntityLoader.java:83)
    at org.hibernate.loader.entity.plan.EntityLoader$Builder.byPrimaryKey(EntityLoader.java:77)
    at org.hibernate.loader.entity.plan.AbstractBatchingEntityLoaderBuilder.buildNonBatchingLoader(AbstractBatchingEntityLoaderBuilder.java:30)
    at org.hibernate.loader.entity.BatchingEntityLoaderBuilder.buildLoader(BatchingEntityLoaderBuilder.java:59)
    at org.hibernate.persister.entity.AbstractEntityPersister.createEntityLoader(AbstractEntityPersister.java:2254)
    at org.hibernate.persister.entity.AbstractEntityPersister.createEntityLoader(AbstractEntityPersister.java:2276)
    at org.hibernate.persister.entity.AbstractEntityPersister.createLoaders(AbstractEntityPersister.java:3876)
    at org.hibernate.persister.entity.AbstractEntityPersister.postInstantiate(AbstractEntityPersister.java:3858)
    at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:444)
    at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:444)
    at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:879)
    ... 9 more

00:51:40,310 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 4) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "jpa-test-1.0-SNAPSHOT.war")]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"jpa-test-1.0-SNAPSHOT.war#jpa-testdb\"" => "org.jboss.msc.service.StartException in service jboss.persistenceunit.\"jpa-test-1.0-SNAPSHOT.war#jpa-testdb\": javax.persistence.PersistenceException: [PersistenceUnit: jpa-testdb] Unable to build Hibernate SessionFactory
    Caused by: javax.persistence.PersistenceException: [PersistenceUnit: jpa-testdb] Unable to build Hibernate SessionFactory
    Caused by: org.hibernate.loader.MultipleBagFetchException: cannot simultaneously fetch multiple bags: [com.bcplatforms.backend.jpa-test.invoiceRows, com.bcplatforms.backend.User.administrates]"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.persistenceunit.\"jpa-test-1.0-SNAPSHOT.war#jpa-testdb\""],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
00:51:40,312 ERROR [org.jboss.as.server] (management-handler-thread - 4) WFLYSRV0021: Deploy of deployment "jpa-test-1.0-SNAPSHOT.war" was rolled back with the following failure message: 
{
    "WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"jpa-test-1.0-SNAPSHOT.war#jpa-testdb\"" => "org.jboss.msc.service.StartException in service jboss.persistenceunit.\"jpa-test-1.0-SNAPSHOT.war#jpa-testdb\": javax.persistence.PersistenceException: [PersistenceUnit: jpa-testdb] Unable to build Hibernate SessionFactory
    Caused by: javax.persistence.PersistenceException: [PersistenceUnit: jpa-testdb] Unable to build Hibernate SessionFactory
    Caused by: org.hibernate.loader.MultipleBagFetchException: cannot simultaneously fetch multiple bags: [com.bcplatforms.backend.jpa-test.invoiceRows, com.bcplatforms.backend.User.administrates]"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.persistenceunit.\"jpa-test-1.0-SNAPSHOT.war#jpa-testdb\""],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
```

**Comment by mstahv** [comment]
jpa-test? Is it a different project? Can you try with a clean checkout of this project and then just issue "mvn wildfly:run" ?

**Comment by kalwar** [comment]
Sorry about that I renamed your project to jpa-test and messed with few classes... but it is almost identical copy of your project.

**Comment by mstahv** [comment]
That looks like the actual error now, I fixed that just today to this project. A compatibility issue with latest hibernate. There was a code change as well in the changeset that closed this issue:

https://github.com/mstahv/jpa-invoicer/commit/20efef4eda442bbd8f23db48be1b0c32fc131ff1#diff-ce7d77df5219401f85c28a46e30a4d01L23

**Comment by kalwar** [comment]
Thanks a lot. It works now.
