### ISSUE TITLE
Data is not Saved in ElementCollectionTable

### ISSUE THREAD

**Issue by mortoza** [mstahv/jpa-invoicer#8]
Hi
I am trying to use @ElementCollectionTable using your sample codes where you used @ElementCollectionField. It nicely displays the Collection table but unfortunately does not save the data in Embedded table. Your help will be really appreciated (if there is any sample using @ElementCollectionTable that might be also helpful) : 

Here is the details-

Warning:   A system exception occurred during an invocation on EJB InvoiceFacade, method: public void com.inteacc.ejb.AbstractFacade.create(java.lang.Object)
Warning:   javax.ejb.EJBException
    at com.sun.ejb.containers.EJBContainerTransactionManager.processSystemException(EJBContainerTransactionManager.java:748)
    at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:698)
    at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:503)
    at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
    at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2074)
    at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2044)
    at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:220)
    at com.sun.ejb.containers.EJBLocalObjectInvocationHandlerDelegate.invoke(EJBLocalObjectInvocationHandlerDelegate.java:88)
    at com.sun.proxy.$Proxy389.create(Unknown Source)
    at com.inteacc.ejb.**EJB31_Generated__InvoiceFacade__Intf____Bean**.create(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:414)
    at org.jboss.weld.bean.proxy.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:127)
    at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
    at org.jboss.weld.bean.proxy.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:65)
    at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
    at com.inteacc.ejb.InvoiceFacade$Proxy$_$$_Weld$EnterpriseProxy$.create(Unknown Source)
    at com.inteacc.view.invoice.InvoiceVaadin1View.save(InvoiceVaadin1View.java:111)
    at com.inteacc.view.invoice.InvoiceVaadin1View$$Lambda$10/1481596138.onSave(Unknown Source)
    at org.vaadin.maddon.form.AbstractForm.save(AbstractForm.java:202)
    at org.vaadin.maddon.form.AbstractForm$3.buttonClick(AbstractForm.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)

The code at line 111 is:
public void save(Invoice entity) {
        if (entity.getId() == null) { 
            facade1.create(entity);        //line 111
        } else {
            facade1.edit(entity);
        }
        listEntities();
        Notification.show("Saved!");
    }

**Comment by mstahv** [comment]
So this happens on you application, not on this example app?

**Comment by mortoza** [comment]
I couldn't test this stage with the example app due to some other issue that I have reported separately. I used the codes from your example application to use ElementCollectionTable

**Comment by mstahv** [comment]
This example app now deploys properly without haven customs properties set (bypasses oauth login). I tried in GF 4.1 and the ElementCollectionField works just fine and also ElementCollectionTable if you just replace the field with it.

If the example doesn't help you to get started, your you think there is some bug in the field, please open an issue to Viritin project.
